export const questions = [
  {
    questionText:
      "You are a time bomb, tick-tick-ticking. And I have no intention of being around for the boom.",
    answerOptions: [
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: true },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
    ],
  },
  {
    questionText: "Send him to Belize? I'll send YOU to Belize.",
    answerOptions: [
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Walter White", isCorrect: true },
    ],
  },
  {
    questionText: "Name one thing in this world that is non negotiable.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Jesus! Just grow some fucking balls!",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
    ],
  },
  {
    questionText: "Since when do vegans eat fried chicken?",
    answerOptions: [
      { answerText: "Walter White", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: true },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
    ],
  },
  {
    questionText:
      "'Cap'n Cook?' That's not you? Like I said, no one is looking for you.",
    answerOptions: [
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Walter White", isCorrect: true },
    ],
  },
  {
    questionText:
      "If that’s true, if you don’t know who I am, then maybe your best course… would be to tread lightly.",
    answerOptions: [
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Walter White", isCorrect: true },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Did you just bring a bomb into a hospital?",
    answerOptions: [
      { answerText: "Walter White", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: true },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "Someone has to protect this family from the man who protects this family.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: true },
      { answerText: "Ted Beneke", isCorrect: false },
    ],
  },
  {
    questionText: "I am not in danger, Skyler. I AM the danger!",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
    ],
  },
  {
    questionText:
      "This is my own private domicile and I will not be harassed... bitch!",
    answerOptions: [
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: true },
    ],
  },
  {
    questionText: "May his death satisfy you.",
    answerOptions: [
      { answerText: "Gustavo Fring", isCorrect: true },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Stay out of my territory.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
    ],
  },
  {
    questionText: "I'm a criminal, yo.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: true },
      { answerText: "Todd", isCorrect: false },
    ],
  },
  {
    questionText: "Seriously? 'Hello Kitty'?",
    answerOptions: [
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: true },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
    ],
  },
  {
    questionText: "Yeah, bitch! Magnets!",
    answerOptions: [
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: true },
    ],
  },
  {
    questionText:
      "Sitting around, smoking marijuana, eating Cheetos and masturbating do not constitute 'plans'.",
    answerOptions: [
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Walter White", isCorrect: true },
      { answerText: "Gustavo Fring", isCorrect: false },
    ],
  },
  {
    questionText: "So you do have a plan? Yeah, Mr. White! Yeah, science!",
    answerOptions: [
      { answerText: "Jesse Pinkman", isCorrect: true },
      { answerText: "Walter White", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
    ],
  },
  {
    questionText:
      "Congratulations, you’ve just left your family a second-hand Subaru.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: true },
      { answerText: "Gus Fring", isCorrect: false },
    ],
  },
  {
    questionText:
      "You're the smartest guy I ever met, and you're too stupid to see he made up his mind 10 minutes ago.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: true },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
];

/*
const extra_questions = [
  {
    questionText:
      "Put me on your magical boat, man, and sail me down your chocolaty river of meth!",
    answerOptions: [
      { answerText: "Badger", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Shut the f*ck up and let me die in peace.",
    answerOptions: [
      { answerText: "Mike Ehrmantraut", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "I'm sorry, what were you asking me? Oh, yes, that stupid plastic container I asked you to buy. You see, hydrofluoric acid won't eat through plastic; it will however dissolve metal, rock, glass, ceramic. So there's that",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "Alright, tell you what. Both of you pull it out your butts right now, or I go grab a flashlight and some pliers and go exploring.",
    answerOptions: [
      { answerText: "Jesse Pinkman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "My name is ASAC Schrader, and you can go f*ck yourself.",
    answerOptions: [
      { answerText: "Hank Schrader", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "If I ever get anal polyps, I'll know what to name them.",
    answerOptions: [
      { answerText: "Saul Goodman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "You all know exactly who I am. Say my name.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "I do not believe fear to be an effective motivator. I want investment. For now, I'm simply interested in time frame",
    answerOptions: [
      { answerText: "Gustavo Fring", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "Just because you shot Jesse James doesn't mean you are Jesse James.",
    answerOptions: [
      { answerText: "Mike Ehrmantraut", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "Sometimes it just feels better not to talk. At All. About Anything. To Anyone.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "You're my free pass... bitch!",
    answerOptions: [
      { answerText: "Jesse Pinkman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "You won, Walter. You got the job. Do yourself a favor and learn to take yes for an answer.",
    answerOptions: [
      { answerText: "Mike Ehrmantraut", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "No more half-measures, Walter.",
    answerOptions: [
      { answerText: "Mike Ehrmantraut", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "I did it for me. I liked it. I was good at it. And... I was really... I was alive.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "You are not the guy. You're not capable of being the guy. I had a guy but now I don't. You are not the guy.",
    answerOptions: [
      { answerText: "Mike Ehrmantraut", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "When you have children, you always have family. They will always be your priority, your responsibility. And a man, a man provides. And he does it even when he's not appreciated or respected or even loved. He simply bears up and he does it. Because he's a man.",
    answerOptions: [
      { answerText: "Gustavo Fring", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "A guy opens his door and gets shot and you think that of me? No. I am the one who knocks!",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "The thing is, if you just do stuff and nothing happens, what's it all mean? What's the point? Oh right, this whole thing is about self-acceptance.",
    answerOptions: [
      { answerText: "Jesse Pinkman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "What I came to realise is that fear, that's the worst of it. That's the real enemy. So, get up, get out in the real world and you kick that bastard as hard you can right in the teeth.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Speak into the mic, bitch.",
    answerOptions: [
      { answerText: "Jesse Pinkman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Keys, scumbag. It's the universal symbol for keys.",
    answerOptions: [
      { answerText: "Mike Ehrmantraut", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "I’m not saying it’s not bad. It’s bad. But it could be worse.",
    answerOptions: [
      { answerText: "Saul Goodman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "I watched Jane die. I was there. And I watched her die.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "You know how they say 'it's been a pleasure'? Well... it hasn't.",
    answerOptions: [
      { answerText: "Mike Ehrmantraut", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "You do seem to have a little “shit creek” action going… You know, FYI, you can buy a paddle.",
    answerOptions: [
      { answerText: "Saul Goodman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "You need to stop focusing on the darkness behind you. The past is the past. Nothing can change what we’ve done.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Don't drink and drive but if you do, call me.",
    answerOptions: [
      { answerText: "Saul Goodman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "I will put you under the jail.",
    answerOptions: [
      { answerText: "Hank Schrader", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "The Universe is Random. Not Inevitable. It's simple Chaos.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "Do you know how much I make a year? I mean, even if I told you, you wouldn't believe it.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "Smoking marijuana, eating cheetos, and masturbating do not constitute plans in my book.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "If you don’t know who I am, then maybe your best course would be to tread lightly.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Everyone sounds like Meryl Streep with a gun to their head.",
    answerOptions: [
      { answerText: "Mike Ehrmantraut", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Fire in the hole, bitch!",
    answerOptions: [
      { answerText: "Jesse Pinkman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "Hey, tell your douchebag brother-in-law to head towards the light",
    answerOptions: [
      { answerText: "Jesse Pinkman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "All I can do is wait... for the cancer to come back.",
    answerOptions: [
      { answerText: "Skyler White", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "I did it for me. I liked it. I was good at it. And I was really... I was alive.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Buzz buzz buzz",
    answerOptions: [
      { answerText: "The fly", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "Did you know that there's an acceptable level of rat turds that can go into candy bars? It's the government, jack. Even government doesn't care that much about quality. You know what is okay to put in hot dogs? Huh? Pig lips and *beep* But I say, hey, have at it bitches 'cause I love hot dogs.",
    answerOptions: [
      { answerText: "Jesse Pinkman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "I will kill your wife, I will kill your son, I will kill your infant daughter.",
    answerOptions: [
      { answerText: "Gustavo Fring", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Alright, I've got the talking pillow now... Okay?",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "You two suck at peddling meth.",
    answerOptions: [
      { answerText: "Saul Goodman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "They're minerals, Marie! Jesus!",
    answerOptions: [
      { answerText: "Hank Schrader", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "The one that says if I can't kill you, you'll sure as *beep* wish you were dead.",
    answerOptions: [
      { answerText: "Jesse Pinkman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "We tried to poison you. We tried to poison you because you are an insane, degenerate piece of filth and you deserve to die.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "I'm not in the meth business. I'm in the empire business.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Better call Saul!",
    answerOptions: [
      { answerText: "Saul Goodman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Because I say so.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "F*ck you! And your eyebrows!",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "Clearly, his taste in women is the same as his taste in lawyers.",
    answerOptions: [
      { answerText: "Saul Goodman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "Walter Jr., you're my big man. There are going to be some things that you'll come to learn about me in the next few days. But just know that no matter how it may look, I only had you in my heart. Goodbye!",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "Bitch!",
    answerOptions: [
      { answerText: "Jesse Pinkman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "I hide in plain sight, same as you.",
    answerOptions: [
      { answerText: "Gustavo Fring", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText:
      "You don’t want a criminal lawyer. You want a criminal lawyer.",
    answerOptions: [
      { answerText: "Jesse Pinkman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "We're done when I say we're done.",
    answerOptions: [
      { answerText: "Walter White", isCorrect: true },

      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Jesse Pinkman", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
  {
    questionText: "So roll me further bitch!",
    answerOptions: [
      { answerText: "Jesse Pinkman", isCorrect: true },

      { answerText: "Walter White", isCorrect: false },
      { answerText: "Mike Ehrmantraut", isCorrect: false },
      { answerText: "Hank Schrader", isCorrect: false },
      { answerText: "Skyler White", isCorrect: false },
      { answerText: "Gustavo Fring", isCorrect: false },
      { answerText: "Saul Goodman", isCorrect: false },
      { answerText: "Badger", isCorrect: false },
      { answerText: "The fly", isCorrect: false },
      { answerText: "Marie Schrader", isCorrect: false },
      { answerText: "Walter White, Jr.", isCorrect: false },
      { answerText: "Steven Gomez", isCorrect: false },
      { answerText: "Gus Fring", isCorrect: false },
      { answerText: "Skinny Pete", isCorrect: false },
      { answerText: "Todd", isCorrect: false },
      { answerText: "Ted Beneke", isCorrect: false },
      { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
      { answerText: "ASAC George Merkert", isCorrect: false },
      { answerText: "Huell", isCorrect: false },
      { answerText: "Tyrus Kitt", isCorrect: false },
      { answerText: "Jane Margolis", isCorrect: false },
      { answerText: "Carmen Molina", isCorrect: false },
      { answerText: "Andrea Cantillo", isCorrect: false },
      { answerText: "Francesca", isCorrect: false },
      { answerText: "Elliott Schwartz", isCorrect: false },
    ],
  },
];
*/

export const options = [
  { answerText: "Walter White", isCorrect: false },
  { answerText: "Mike Ehrmantraut", isCorrect: false },
  { answerText: "Hank Schrader", isCorrect: false },
  { answerText: "Jesse Pinkman", isCorrect: false },
  { answerText: "Skyler White", isCorrect: false },
  { answerText: "Gustavo Fring", isCorrect: false },
  { answerText: "Saul Goodman", isCorrect: false },
  { answerText: "Badger", isCorrect: false },
  { answerText: "The fly", isCorrect: false },
  { answerText: "Marie Schrader", isCorrect: false },
  { answerText: "Walter White, Jr.", isCorrect: false },
  { answerText: "Steven Gomez", isCorrect: false },
  { answerText: "Gus Fring", isCorrect: false },
  { answerText: "Skinny Pete", isCorrect: false },
  { answerText: "Todd", isCorrect: false },
  { answerText: "Ted Beneke", isCorrect: false },
  { answerText: "Lydia Rodarte-Quayle", isCorrect: false },
  { answerText: "ASAC George Merkert", isCorrect: false },
  { answerText: "Huell", isCorrect: false },
  { answerText: "Tyrus Kitt", isCorrect: false },
  { answerText: "Jane Margolis", isCorrect: false },
  { answerText: "Carmen Molina", isCorrect: false },
  { answerText: "Andrea Cantillo", isCorrect: false },
  { answerText: "Francesca", isCorrect: false },
  { answerText: "Elliott Schwartz", isCorrect: false },
];
